- src/teletype.h
I managed to get [flycheck][] working with properly with emacs and avr32, anyway it's flagged a few things... in particular a bunch of uninitialized fields.
So, as far as I can tell the field `t` is not used in `tele_var_t` and `tele_array_t`, I'm guessing it's left over from some previous use?
I haven't tested this change on hardware...
[flycheck]: http://www.flycheck.org/
> remove unused t from tele_var_t and tele_array_t

- .travis.yml
Cribbed from https://github.com/samdoshi/teletype/commit/0a51dd8c1efd6fc3865cc624b80d52108b2ec5af.
Feels dodgy to use Sam's avr32-gnu-toolchain zip but maybe sufficient for a first cut?
I also think we should update the `language` to C (and if necessary the build bits) in another pass.
> Travis config first cut.

- module/main.c
implementation for #16. key hold will now work for all key presses by default. also:
- key processing extracted into its own function `process_keypress`
- removed global mod_ variables (for now replaced by a global variable `mod_key`, eventually should be probably extracted into `input_state` or something like that)
- fixed several bugs where pattern length wasn't properly updated in `TRACK` mode
- fixed a bug with `[` and `]` not updating values in `TRACK` mode
- `ENTER` will now always move to the next step, not just when on the last step
@tehn @samdoshi
> key behavior: repeat on hold, bug fixes

- src/ops/hardware.c
- src/ops/hardware.h
- src/ops/op.c
- src/ops/op.h
implementation for `LV.CV` and `CY.CV` remote commands
- these will return value at the specified CV output for Levels and Cycles respectively
- as discussed these are only readable for now
- ansible will return 0 for CV number outside of 1..4 range
> LV.CV | CY.CV implementation

- .editorconfig
- docs/modes.md
- utils/docs.py
- utils/templates/docs.css
- utils/templates/op_table.jinja2.md
- utils/templates/template.html5
Not ready for merge!
This PR makes some UX enhancements to the pandoc generated HTML5 Teletype docs.
---
Things fixed in this PR:
- currently, wide tables overflow the horizontal width of smaller screens.
- **I’ve updated things to fill better across screen sizes. The tables are still not great, but they are usable.**
- In past projects I’ve worked on, we’ve decided that links outside of the content you are currently looking at should open in a new tab so as to prevent context switching.
- this shouldn’t be difficult because it’s already reflected in the URL as a hash
---
Things I didn't get to.
- Quantization scale content is repeated
- It’s fine that it’s repeated visually, need to see if the content is repeated in the repo…could lead to change drift
- Include footnote sources under …
> Teletype Docs UX Enhancements

- docs/quickstart.md
Straightforward docs change...relevant to >= 2.0.0 releases.
Figured it was easiest to just commit to master and get this into 2.1.0 rather than try to backport to 2.0.0/2.0.1.
> Fixes #108 ~ key docs bug

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Adds a template for new Github issues.
It was suggested in this [PR](https://github.com/monome/teletype/pull/103) by @samdoshi 
Only way to test it is to merge it. I've checked the markdown formatting in Atom Github-flavor markdown preview and it worked ok.
I'm concerned this is too heavy weight and might intimidate new issue writers. The PR is editable by maintainers, so I'd suggest making edits directly rather than waiting for me to edit it based on feedback. Think of this PR as an initial draft to get thoughts going.
> New Issue Template

- CHANGELOG.md
- src/ops/maths.c
Corrects the functionality of the JI op. It previously gave raw ratio conversions that didn't relate to the 1volt / octave standard in Eurorack.
Uses a prime-factorization technique, which goes up to 13-limit tuning. Should be sufficient for most musical use-cases. Every extra prime extends worst case search time for invalid ratios.
Presently an invalid ratio (one which cannot be factored with primes of
13 or less) simply returns 0 (the base pitch). All results are scaled
between 0 and V 1.
The weird list of constants is calculated with a logarithmic function, representing some kind of musical fraction of the octave. These constants can simply be composed with addition (numerator) and subtraction (denominator) to find the JI result. Prime factorization is used to break down composite …
> JI op corrected to map to volt/octave values

- CHANGELOG.md
- src/ops/maths.c
Removed octave-wrapping behaviour. Now returns exactly the entered
ratio.
> JI op rework

- CHANGELOG.md
- docs/ops/controlflow.toml
- src/state.c
Propagates I values to child exec states (SCRIPT calls)
Does the same for IF condition state
https://llllllll.co/t/teletype-asynchronous-tasks-and-variable-scope/11611
```
1: L 1 4: SCRIPT 2
2: TR.P I
```
All 4 triggers should fire.
```
1: IF 0: BRK
SCRIPT 2
2: ELSE: TR.P 1
```
Trigger 1 should fire.
Changes in 2.1 to L / I / IF to fix bugs with concurrency limited I's scope to an execution context.  Copying I forward through execution depths is desirable so that scripts can use I to know where the parent loop is.
* [*] updated CHANGELOG.md
* [*] updated the documentation
> Fixes #140 by copying I to child exec state

- docs/intro.md
- module/Makefile
- module/live_mode.c
- utils/cheatsheet.py
- utils/common/__init__.py
- utils/docs.py
- utils/templates/latex_preamble.jinja2.md
This does a few things:
- remove hardcoded references to version in both c code and docs md
- updates module make command that gets git version to use the tag to grab the current semantic teletype version
- updates live mode prompt to use the updated version string (same formatting--user won't notice any changes)
- updates both docs (html/pdf) and cheatsheet to include version in the title.
---
I didn't run clang, but the c changes are so small I can't imagine a formatting issue snuck in.
I conformed to pep8 using flake8 for all the python code.  @samdoshi There seems to be a few `f"..."` strings that were getting picked up as invalid syntax from running flake8 on the commandline as well as with the atom package I downloaded...I didn't edit them, didn't see any error output when running …
> programatically grab version for docs and live mode

- simulator/Makefile
- tests/Makefile
This PR fixes up the build. https://github.com/monome/teletype/pull/152 introduced W/ ops, but we need to update `simulator/Makefile` and `tests/Makefile` to depend on the new object, `src/ops/wslash.o`.
N/A
* Check Travis
* Build manually
N/A
N/A
> Simulator & tests depend on src/ops/wslash.o

- src/chaos.h
- tests/op_mod_tests.c
1. Fixes a typo in a `#define` in `src/chaos.h`
2. Fixes a SEGFAULT I get when running the tests after compiling with clang.
N/A
1. Compile as normal and ensure tests continue to pass.
2. Compile with clang and ensure tests continue to pass.
Here's what I was getting before this change:
```
$ lldb -e tests/tests
(lldb) target create "tests/tests"
Current executable set to 'tests/tests' (x86_64).
(lldb) run
Process 14328 launched: '/Users/mroberts/src/personal/teletype/tests/tests' (x86_64)
* Suite match_token_suite:
..
2 tests - 2 passed, 0 failed, 0 skipped (132 ticks, 0.000 sec)
* Suite op_mod_suite:
...tests was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 14328 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = …
```
> Fixes a SEGFAULT I get when running the tests after compiling with clang

- CHANGELOG.md
- docs/ops/delay.toml
- src/match_token.rl
- src/ops/delay.c
- src/ops/delay.h
- src/ops/op.c
- src/ops/op_enum.h
- src/state.h
added ```DEL.X``` and ```DEL.R``` ops allowing for chained(multiple) delays at spaced intervals.  added common delay add function for all delay ops to save code space.  additionally increased the maximum number of delays from 8 to 16.
https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/27?u=alphacactus
tested both old and new delay ops with variable delay times and number of delays.  tested edge cases such as calling ```DEL.X``` for zero delays, delay times of zero, and negative delay times.
> DEL.X / DEL.R ops

- module/flash.c
on flash_reset detection (checking magic number in `flash_prepare`) blink a light and wait for confirmation by pressing key down. otherwise it times out and doesn't run.
works perfectly well for newly flashed units. we'd need to see the bug-state to trigger this, which isn't known. it's a protection measure at this point.
> require confirm for flash initialization

- module/flash.c
- module/flash.h
- module/main.c
further fixes for flash initialization:
- added a screen with a warning
- previous change would always init with blank scenes
- added a safeguard for preset_no
> fixes for flash initialization

- module/Makefile
Without specifying a shell, make will use `/bin/sh`, which on some environments (Ubuntu, and therefore [this](https://hub.docker.com/r/dewb/monome-build/) Dockerfile) is not `bash`. This causes redirection to fail in the bit that generates the git sha1 to embed in the firmware. Also `git describe --always --dirty` was winding up with two different version numbers in the string displayed on Teletype, like `3.0.0 v2.2.0-alpha.7-244` as well as the wrong tag for some reason, this change adds `--exclude '*'` to omit tags in this part so you just get a version + sha like `3.0.0 0F3DAA7-DIRTY`.
This was causing some confusion because the version number was coming out weird from my builds: [1](https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/348), …
> bugfix: git sha1 script requires bash

- module/main.c
Fixes #181 - changes for `$.POL` broke input processing when `DEVICE.FLIP`ped
https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/364
`DEVICE.FLIP` and check each trigger input.
https://github.com/monome/teletype/issues/181
> fix $.POL change that broke inputs w/ DEVICE.FLIP

- CHANGELOG.md
- module/main.c
Changes what appears to be a typo manually triggering `adcTimer` instead of `cvTimer` in `tele_cv`, which was causing DACs not to update until the CV timer expires when using `CV` ops.
https://llllllll.co/t/teletype-timing-issues-cv-edition/24193/9?u=csboling
Report from testing with an oscilloscope on [Lines](https://llllllll.co/t/teletype-timing-issues-cv-edition/24193/14): "CV state changes have c. 200us of latency + c. 500us of jitter after this update" (down from as much as 6ms)
> bugfix: manually trigger cvTimer on cv change

- CHANGELOG.md
- docs/ops/controlflow.toml
- src/ops/controlflow.c
Tweaks the range check in the `SCRIPT` op so you can use `SCRIPT 9` or `SCRIPT 10` to call metro or init, respectively. This is consistent with the numbering used by the function keys and the grid ops and can be useful for programmatically re-initializing a scene, humanizing a clock, etc.
https://llllllll.co/t/teletype-workflow-basics-and-questions/12392/766
Place triggers in metro and init scripts, call them manually with `SCRIPT 9` and `SCRIPT 10` from live mode.
> Call init or metro with SCRIPT op

- CHANGELOG.md
- docs/ops/ansible.toml
- module/help_mode.c
- src/match_token.rl
- src/ops/ansible.c
- src/ops/ansible.h
- src/ops/op.c
- src/ops/op_enum.h
Adds a teletype op `KR.DUR` for reading the trigger pulse duration from Kria. See https://github.com/monome/ansible/pull/74
https://llllllll.co/t/ansible-development-and-beta-firmware-discussion/23118/166
Patch Ansible TR 1 to Teletype input 1 and put `X KR.DUR 1` in script 1. Monitor variables in live mode to see `X` change to the trigger duration in milliseconds when Kria reaches a new step.
> `KR.DUR` getter op for kria duration

- CHANGELOG.md
- module/edit_mode.c
- module/main.c
When `M.ACT` is 0, dim the `M` in the line editor prompt on the metro script, to match muted scripts. Also fix an out-of-bounds array access that I don't think was causing any trouble but could make this feature behave incorrectly when new members are added to `scene_variables_t` in the future.
https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/408?u=csboling
While editing the metro script, use CTRL+F9 to toggle the metro on and off, and see the `M` dim to match the brightness of muted scripts. The same behavior is seen when running `M.ACT FLIP` manually.
> edit mode: dim M when metro inactive, fix out of bounds array access

- CHANGELOG.md
- docs/keys.md
- module/help_mode.c
- module/pattern_mode.c
- module/pattern_mode.h
Adds the following keybindings to pattern/tracker mode:
```
ALT-[ ]|SEMITONE UP, DOWN
CTRL-[ ]|FIFTH UP, DOWN
SH-[ ]|OCTAVE UP, DOWN
ALT-<0-9>|NUM SEMITONES UP
// 0 = 10 and 1 = 11
SH-ALT-<0-9>|NUM SEMITONES DOWN
// 0 = 10 and 1 = 11
```
Demo video: https://www.youtube.com/watch?v=gxOZY_MgsvE
https://llllllll.co/t/teletype-firmware-discussion/13961/41
1. Enter Pattern/Tracker Mode
2. Try key commands listed above
3. Verify values entered match values in N table
NOTE: `make format` formatted a bunch of lines in help_mode.c that were not in my original changeset
> Pattern mode key bindings

- module/flash.c
initialize min and max values for the `FADER` op so that they aren't garbage prior to first calibration
https://llllllll.co/t/teletype-3-2-0-release/31530/32?u=discohead
need TT with clean flash and a Faderbank, before calibrating the `FADER` op the values should at least be sensible
> initialize fb min max values

- module/usb_disk_mode.c
fixes issue #172 (negative pattern values incorrect after USB read)
place some negative values in a pattern, save to USB, then read from USB. 
test edge cases (-32768, 32767).
issue #172
> fix for #172

- CHANGELOG.md
- docs/ops/variables.toml
- src/ops/variables.c
Previously running `LAST SCRIPT` in live mode was equivalent to running `LAST 0` - since there is no script 0, this would always return 0. Changes this so that it gives the time since the init script was run, since this matches the documentation.
Use `LAST SCRIPT` in live mode to check the time. Press F10 to trigger the init script manually and check again.
Fixes #193
> LAST SCRIPT in live mode should give time since I script

- CHANGELOG.md
- docs/ops/delay.toml
- docs/whats_new.md
- module/help_mode.c
- src/match_token.rl
- src/ops/delay.c
- src/ops/delay.h
- src/ops/op.c
- src/ops/op_enum.h
Adds new variant of `DEL.R/X` called `DEL.G`. It operates in the same way as `DEL.R`, but each successive repeat is multiplied by the fraction given in the argument. This allows easy creation of bouncing balls and other interesting rhythmic effects. 
The implementation is largely based on the previous work done for `DEL.R/X`.
https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/39?u=jngpng
Try `DEL.G` with a variety of settings. `DEL.G 10 100 2 3: TR.P 1` should produce a bouncing-ball pattern. `DEL.G 10 100 5 4: TR.P 1` should produce something like a trill or roll.
> Add DEL.G exponential delay

- CHANGELOG.md
- docs/ops/delay.toml
- docs/whats_new.md
- src/match_token.rl
- src/scanner.rl
adds ability to specify numbers in binary and hex format. binary numbers must start with `B` prefix, hex - with `X` prefix. negative numbers in binary/hex not supported (not likely to be used for negative numbers i think).
also fixed warnings for tests and simulator builds and fixed a typo for `DEL.G` op.
https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/81
try various numbers
> ability to specify numbers in binary and hex formats

- CHANGELOG.md
- utils/templates/template.html
Previously, the `onchangehash` handler would run `fixBr` every time
the user navigated to a new hash. The `fixBr` function takes a long
time to execute because it causes lots of reflows. This commit
removes the (seemingly) unnecessary `linksToNewTab` and `fixBr` function calls
from the onhashchange handler by moving the necessary code to a new helper
function.
1. Build docs
2. Open `teletype.html`
3. Navigate to various sections in the navigation pane (should be almost instant now)
4. Try navigating backward/forward in the browser
> improve performance when navigating in docs

- CHANGELOG.md
- docs/whats_new.md
- src/ops/variables.c
fixes issue #222
https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/161
add this to script 1: `A LAST SCRIPT`, switch to live screen, trigger script 1 and watch variable `A`. it should reset count each time it's called.
https://github.com/monome/teletype/issues/222
> fix for "LAST n is broken for script 1"

- src/match_token.rl
- src/ops/delay.c
- src/ops/maths.c
- src/ops/op.c
- a fix for `X...` and `B...` number formats not producing correct values for numbers 0x8000 and higher.
- ran clang-format on files changed in https://github.com/monome/teletype/pull/225
https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/194
try inputting hex numbers in the range of 0x8000 or higher
try inputting binary numbers in the range 0b1000000000000000 or higher
> fix for X and B not working for negative values, formatting

- docs/intro.md
- utils/templates/template.html
Adds title metadata for generated HTML documentation. Deletes HTML chunk which displays metadata on the page, hidden behind the menu, and not rendered when the title is not set
Tested it working on a local build
I already made a PR here https://github.com/monome/docs/pull/271 before learning they were generated.
> Adds title frontmatter to docs for HMTL metadata

- src/command.c
- src/command.h
- src/match_token.rl
- src/teletype.c
previously, numbers entered using `X..` | `B..` | `R..` formats would get converted to decimal whenever a line containing them would be entered. with this change the number format will be preserved.
ensure number formats are preserved when:
- entering them in live screen and then using history
- entering numbers in script editing
- storing scenes to USB and restoring them from USB
test `X0`, `B0`, `R0`.
> preserve number format

- CHANGELOG.md
- docs/ops/earthsea.toml
- src/match_token.rl
- src/ops/earthsea.c
- src/ops/earthsea.h
- src/ops/op.c
- src/ops/op_enum.h
Adds an `ES.CV` op to read the current pitch for a given output channel from either Trilogy Earthsea or Ansible Earthsea.
This came to my attention on discord, not sure if it's been discussed on lines before.
Connect ii to Ansible running the patch in https://github.com/monome/ansible/pull/94 and hosting a grid. Switch Ansible into Earthsea mode. Check that `ES.CV 1` - `ES.CV 4` read as expected as multiple Earthsea keys are held.
> add ES.CV ii op

- docs/ops/maths.toml
Super small beauty fix in documention.
> docs: removed superfluous parentheses

- README.md
The list of steps for adding a new OP or MOD was incomplete. This PR extends the README to make it clearer what needs to be done.
> Add missing steps from the add-a-new-op list

- src/table.c
- src/table.h
Changes the types of data in the src/tables.c file. I made some guesses about which vals should be signed vs unsigned, but i reduced everything to the smallest storage type that would fit the data.
It saves ~1.5kB in ROM usage.
Every command that uses table data should be tested. I haven't been using TT enough to know what those commands are, so I'm not comfortable testing this.
Please don't merge until it has been tested.
> reduce type size of table data for less ROM. UNTESTED

- module/config.mk
changed to 200k. tt now has its own lds in libavr32 because ansible doesn't want 200k.
> adjust nvram

- module/config.mk
Sets a custom symbol for the linker script, causing the NVRAM to be moved further into the flash address space. This was necessitated as the TT program has grown beyond the allotted 256KB flash reserved for it.
NVRAM is just a marker in the flash memory space which enables an additional interface for read/writing data. It does *not* require any special hardware support, and the location is arbitrary - the flash memory it controls is homogeneous.
TT uses the NVRAM address marker as the basis for all non-volatile data storage (Saved scenes, and calibration data). The 512KB of flash memory was previously split 256/256kB between program/data (the default). This PR changes the split to 312/200kB. The current usage of NVRAM is ~198kB, so if any substantial amount of data is added to the stored …
> Customize NVRAM address to enable larger core flash program

- CHANGELOG.md
- docs/keys.md
- module/line_editor.c
- Adds "delete to end of word" command for line editing. Bound to `alt-d`.
- Adds additional keybinds for move forwards/backwards by word (`alt-f` and `alt-b`).
- Updates "move forward/backwards by word" commands to skip all intervening space between the cursor and the word e.g. in the line "A_ _ _B"  with the cursor at B, moving backwards by word will place the cursor at A instead of moving one space back per key press.
[Discussion here](https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/427?u=svin).
- Type text in live or edit mode. Use `alt-f`, `alt-b`, `alt-d` keybinds.
- Chosen new keybinds match existing use of [emacs keybinds](https://www.gnu.org/software/emacs/manual/html_node/emacs/Moving-Point.html).
> Improve line editor movement. Add "delete to end of word" command.

- CHANGELOG.md
- docs/ops/controlflow.toml
- docs/whats_new.md
- module/flash.c
- module/flash.h
- module/help_mode.c
- module/main.c
- module/preset_r_mode.c
- module/usb_disk_mode.c
- simulator/tt.c
- src/match_token.rl
- src/ops/controlflow.c
- src/ops/controlflow.h
- src/ops/op.c
- src/ops/op_enum.h
- src/teletype_io.h
- tests/main.c
This op loads a scene without loading the scenes pattern data, similar to `SCENE.G` for grid configuration.
Create two scenes with different pattern data. Load the first scene. Use `SCENE.P` to load the second scene. Confirm that the pattern data has stayed the same, instead of loading pattern data from the second scene.
The idea behind this feature is to be able to jam with the same set of pattern data across multiple scenes.
> Load scene while keeping current pattern state

- CHANGELOG.md
- docs/ops/controlflow.toml
- docs/whats_new.md
- src/match_token.rl
- src/ops/controlflow.c
- src/ops/controlflow.h
- src/ops/op.c
- src/ops/op_enum.h
Adds an `EV` alias for the `EVERY` op to save character space.
Comment on Lines: https://llllllll.co/t/teletype-3-2-feature-requests-and-discussions/32052/443
Use `EV` instead of `EVERY` in a script.
> Add `EV` alias for `EVERY` op

- src/ops/maths.c
setting scale with N.B or N.BX with 13-15 bits, will only use the first 12 bits, instead of R111111111111
https://llllllll.co/t/teletype-4-0-0-pre-release-beta-ready-for-testing/45871/45
N.B(X) r s, should only set first 12 bits (when s positive)
> N.B and N.BX: disregard bits beyond bit 12 (except when negative, = presets)

- CHANGELOG.md
- docs/whats_new.md
- module/flash.c
- module/grid.c
- module/main.c
- simulator/tt.c
- src/match_token.rl
- src/ops/maths.c
- src/ops/op.c
- src/ops/op_enum.h
- src/ops/telex.c
- src/ops/telex.h
- tests/main.c
several changes based on 4.0.0 beta testing:
- added missing entries to changelog and what's new
- logical operators should treat all non zero values as `true`, not just positive values
- better rendering for fine grid faders
- fixed `SCENE` crashing if parameter was out of bounds
- added alias `TI.PRM.CALIB` (was already in the docs)
https://llllllll.co/t/teletype-4-0-0-pre-release-beta-ready-for-testing/45871
for logical ops, try `&& -1 -1` and `|| -1 -1` - both should return `true`
for `SCENE`, try executing with parameter out of 0..31 bounds
> various fixes

- utils/cheatsheet.py
Just removes duplicate cheatsheet section
* [n/a] updated the documentation
* [n/a] updated `help_mode.c` (if applicable)
* [n/a] run `make format` on each commit
* [n/a] run tests # docs still build fine locally (debian)
> Remove duplicate Disting cheatsheet section

- CHANGELOG.md
- docs/whats_new.md
- src/ops/controlflow.c
- tests/process_tests.c
The docs for PROB say "potentially execute command with probability `x` (0-100)"
The current behaviour is that x maps to a probability of x/101. x = 100 executes with the probability of 99.01%
This adjusts the behaviour so that x maps to a probability of x%.
I added a test for PROB 100, but anything probability related is messy to test, so feel free to reject that part.
I found a random youtube comment mentioning this, but I did find a mention on lines:
https://llllllll.co/t/teletype-workflow-basics-and-questions/12392/640
#1
X 0
L 1 10000: $ 2
#2
PROB 100: X + X 1
After running script 1, X should be 10,000. It is ~9900 each time.
Unless I missed it, there wasn't an existing open (or closed) issue. Shall I file one for tracking?
* Documentation was correct.
* No change required.
> Adjust mod_PROB_func to conform to the docs

- CHANGELOG.md
- docs/whats_new.md
- module/grid.c
fixes a bug when `G.FDR` in certain configurations would cause the grid visualizer to render it incorrectly
https://llllllll.co/t/teletype-4-0-0/46706/61
see the above link
> fix bug with G.FDR not being rendered in grid visualizer properly

- CHANGELOG.md
- docs/Makefile
- docs/whats_new.md
- utils/templates/template.html
On some browsers (Chrome and Safari, but not Firefox) the Teletype manual has started to take up to 20 seconds to render the main content area after the page loads.
This rearranges some of the JS code in the HTML version of the manual to reduce reflow and improve the perceived time to load the page. Specifically, it:
* manipulates `textContent` rather than `innerText` to avoid forcing a reflow
* delays unhiding the main content area until all DOM modifications are complete, further preventing reflow
* renames some of the functions to reflect their current behavior
With the profiler on, in current Chrome 92.0.4515.159/Win10, this drops the time to final paint from around 20s to around 700ms.
1. Build the docs
2. Open `teletype.html` in Chrome 92 or Safari/iOS 14.71
3. Observe that the page …
> Improve page load time in Chrome/Safari by reducing forced reflow

- CHANGELOG.md
- docs/whats_new.md
- src/teletype.c
- src/teletype.h
This change stores the currently executing command in a local buffer during each call to `process_command`.  This ensures that when the scene changes, the operation map in `process_command` still points into the same code upon which it was based.  In this way we avoid undefined behavior when the global scene data is replaced while a command is running (i.e., when `SCENE` is executed).  Changing scenes from while code is running is still full of surprises, but they are well-defined.
https://llllllll.co/t/teletype-scene-x-op-users-of-that-op-chime-in/45833/23?u=3-foot-1
Run the scenes in the cited lines thread before and after applying the PR.  Before the change, A will be 9 and C will be 7.  After the change, A will be 18 and C will remain unchanged.
Extensive discussion in the_dev_zone on …
> Buffer each command line in process_command

- CHANGELOG.md
- docs/whats_new.md
- src/ops/crow.c
Corrects a typo that prevents the `CROW.Q3` op from working.
Connect crow to teletype via i2c; set up a crow event handler that responds to `CROW.Q3` and produces visible output in druid; invoke `CROW.Q3` on teletype; observe that the event handler is called with the PR, but not on the unpatched main branch.
> Fix CROW_Q3 operation

- CHANGELOG.md
- docs/whats_new.md
- src/ops/patterns.c
- tests/process_tests.c
Fixes an error where `P.ROT n` does nothing when `n == P.END - P.START`.
I.e., if we have four values in a pattern:
```
0: 1
1: 2
2: 3
3: 4
```
and `P.START` is 0 and `P.END` is 3, `P.ROT 3` should result in:
```
0: 2
1: 3
2: 4
3: 1
```
Instead, it is a no-op.
https://llllllll.co/t/teletype-workflow-basics-and-questions/12392/1821
Create the pattern shown above and run `P.ROT 3`.
> Fix off-by-one error in P.ROT

- src/scene_serialization.c
Fixes bug where # in a command would cause scene restore to fail.
NB: Needs testing on hardware TT. Ive tested it only on an alt firmware.
> Adding fix for # bug

- CHANGELOG.md
- docs/whats_new.md
- src/ops/maths.c
fixes `BPM` op rounding error
execute `BPM 375`, it should return 160 instead of 159
> fix BPM rounding error

- CHANGELOG.md
- docs/whats_new.md
- src/ops/midi.c
fixes the issue with MIDI IN ops returning 0-based channel number instead of 1-based.
https://llllllll.co/t/teletype-midi-in-ops/32868/138
connect a MIDI controller and confirm that the channel number matches the actual one.
> Fix MIDI IN ops channel being off by 1

- CHANGELOG.md
- docs/whats_new.md
- module/main.c
- simulator/tt.c
- src/ops/hardware.c
- src/ops/init.c
- src/state.c
- src/state.h
- src/teletype.c
- src/teletype.h
- src/teletype_io.h
- tests/main.c
previously, TR pulses were processed by `tele_tick` which gets triggered by a 10ms timer, which resulted in the actual pulse length being off by up to 9ms. this PR introduces dedicated timers for each TR output to improve the accuracy. as there are only 4 trigger outputs, i don't think adding 4 timers should make any impact.
additionally, i fixed a bug i discovered where killing delays would not restore TR outputs that had a pulse in progress.
i tested this with a scope and confirmed that the pulse time matches the one set with `TR.TIME`. also confirmed TR pulses work in general - triggering different outputs, changing the pulse time while a pulse is in progress, killing delays.
> improve TR.P accuracy

- README.md
[TinyTeX](https://yihui.org/tinytex/) is my daily driver for LaTeX and has been for several years. I appreciate that it's a smaller install and doesn't force needless editors on me. I nuked my install and documented what appears to be needed to make the docs on my Mac; here they are as a suggested update to the README.
This would close #265.
> Suggest TinyTeX as docs-building toolchain

- .clang-format
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/test.yml
- module/edit_mode.c
- module/grid.c
- module/help_mode.c
- module/line_editor.c
- module/live_mode.c
- module/main.c
- module/pattern_mode.c
- src/ops/hardware.c
- src/ops/justfriends.c
- src/ops/maths.c
- src/ops/queue.c
- src/scene_serialization.c
- tests/log.c
- tests/log.h
- tests/main.c
- tests/match_token_tests.c
- tests/op_mod_tests.c
- tests/parser_tests.c
- tests/process_tests.c
- tests/turtle_tests.c
Adds clang-format to the Actions workflow on pull requests.
This also removes the "did you run tests?" and "did you run make format?" manual questions in the template, since they're presumably now redundant with the automated status checks.
If clang-format finds formatting issues, the status check will fail, and the suggested changes will be shown in the Actions log in diff format, for example:
```
--- module/flash.c	(original)
+++ module/flash.c	(reformatted)
@@ -57,10 +57,8 @@
while (confirm == 1 && (++counter < TIMEOUT)) {
confirm = gpio_get_pin_value(NMI);
if ((counter % 1000) == 0) {
-                if (++toggle % 2)
-                    gpio_set_pin_low(B11);
-                else
-                    gpio_set_pin_high(B11);
+                if (++toggle % 2) gpio_set_pin_low(B11); …
```
> Enforce clang-format in CI

- CHANGELOG.md
- docs/ops/maths.toml
- docs/whats_new.md
Adjusts the documentation for the N.CS scales to match the implementation in [table.c](https://github.com/monome/teletype/blob/7041e67742a84e93c4f0d2797348e00d5a76dd99/src/table.c#L135)
N.CS introduced here: https://llllllll.co/t/teletype-firmware-discussion/13961/49
Compare the documentation to the results of the N.CS op on scales 7 and 8.
I noticed the issue when I was comparing the N.CS implementation to the similar norns functionality in https://github.com/monome/norns/pull/1688.
(n/a)
> Correctly document N.CS scales 7 & 8

- docs/ops/queue.md
Streamlines the summary paragraphs for the Queue section of the docs, prompted by the specific issue noted in #296.
n/a
n/a
n/a
* n/a updated `CHANGELOG.md` and `whats_new.md`
* n/a updated `help_mode.c` (if applicable)
> Update queue docs (addressing #296)

- CHANGELOG.md
- docs/whats_new.md
- module/flash.c
- module/flash.h
- module/main.c
This folds in changes necessary to build the TT source for x64/ARM and use it in VCV Rack. There is no direct hardware benefit to these changes, but they should be benign.
The indirect benefit to merging this is that afterwards any branch off main can be tested in VCV Rack prior to being tested in hardware, without having to first pollute the feature branch with Rack compatibility patches.
https://llllllll.co/t/monome-vcv-rack-ports-development-log/10337
Build, flash to module, test scene save and restore.
n/a
n/a
* (n/a) updated the documentation
* (n/a) updated `help_mode.c` (if applicable)
> Bring x64/ARM build compatibility patches into main

- src/ops/delay.c
- src/scene_serialization.c
- src/state.h
- src/teletype.c
this PR fixes 2 issues:
- grid fader state wasn't deserialized properly after this change: https://github.com/monome/teletype/pull/306
- ops for function parameters `I1` and `I2` (introduced here: https://github.com/monome/teletype/pull/313) were returning 0 if used in a `DEL`
for the serialization bug:
- set grid button and fader states to random values
- save the scene to flash and then to USB
- copy the tt##.txt file to tt##s.txt file
- load the scene from USB, then save it as a new scene
- save the new scene to USB
- compare the files
for the function parameters bug:
```
X 0
$S1 4 12345
BRK
DEL 100: X I1
```
executing the script should set `X` to 12345.
i didn't update changelog/whatsnew since both bugs were introduced in this version.
> fixes for function params and grid serialization

- CHANGELOG.md
- docs/whats_new.md
- src/ops/disting.c
fixes the disting ex looper ops that got broken when the disting ex parameter indexes changed in the latest disting ex firmware updates.
https://llllllll.co/t/teletype-disting-ex-integration/33929/205
by executing the ops
> fix disting ex looper ops

- .github/workflows/test.yml
- .gitignore
- docs/Makefile
Further tweaks the artifact production process in Actions to include the HTML docs and also combine everything into a release .zip with the firmware update scripts.
* n/a updated `CHANGELOG.md` and `whats_new.md`
* n/a updated the documentation
* n/a updated `help_mode.c` (if applicable)
> Combine artifacts into a single release zip

- CHANGELOG.md
- docs/whats_new.md
- module/help_mode.c
It's possible for help mode reverse search to index beyond the bounds of a page. On hardware, this is likely not a hard crash, but it could lead to unexpected behavior. On VCV Rack hitting this results in a crash (see https://github.com/Dewb/monome-rack/issues/206).
See steps to reproduce in https://github.com/Dewb/monome-rack/issues/206
> Fix potential crash in help mode reverse search

- docs/ops/i2c2midi.toml
I noticed that the formatting of the last part of the docs for i2c2midi-commands is screwed up (from the entry for "I2M.C.ROT x y" onwards) because of a missing backtick. This PR adds that missing backtick to unscrew said formatting.
> Fix formatting error because of missing backtick

- Makefile
- module/help_mode.c
fixes format warning in CI introduced in #336
n/a
n/a
Looks like local clang-format results and CI results are not consistent, c-f didn't complain for me locally. (Apple clang 15.0.0, latest git clang-format integration via homebrew.)
* (n/a) updated `CHANGELOG.md` and `whats_new.md`
* (n/a) updated the documentation
* (n/a) updated `help_mode.c` (if applicable)
> satisfy CI clang-format
