src/teletype.c
src/teletype.h

change tele_var_t.func from void (*func)(uint8_t) to void (*func)(void)

---

module/main.c

fixes to accomodate changes to `libavr32` for aleph compatibility.

aleph libavr32

---

module/main.c

msgpack ref link

---

src/ops/hardware.c
src/ops/hardware.h
src/ops/op.c
src/ops/op.h

ansible/levels had the wrong nomenclature. apologies for the mess.

ii message correction

---

simulator/Makefile
tests/Makefile

this should address issue https://github.com/monome/teletype/issues/65

change simulator makefile to pull euclidean bits from libavr32

---

docs/modes.md
module/preset_w_mode.c

Scene write mode now allows line insert with shift-enter.

Fixes #3 by assigning shift-enter to line insert

---

.gitignore
CHANGELOG.md
Makefile
docs/Makefile
docs/cheatsheet/cheatsheet.tex
docs/ops/patterns.toml
utils/cheatsheet.py
utils/common/__init__.py
utils/docs.py

Adds code to generate a cheat sheet PDF
https://llllllll.co/t/teletype-docs-enhancements-docs-are-live-cheatsheet-will-be-live-very-shortly/8612/132?u=sam
```bash
cd docs
make
```
Example PDF attached: [cheatsheet.pdf](https://github.com/monome/teletype/files/1381830/cheatsheet.pdf)

Add cheat sheet

---

module/main.c
simulator/tt.c
src/ops/hardware.c
src/teletype_io.h
tests/main.c

fix for https://github.com/monome/teletype/issues/132
https://llllllll.co/t/teletype-in-cv-read-latency/10142
see the issue

fix for IN latency

---

CHANGELOG.md
docs/keys.md
docs/ops/controlflow.toml
docs/ops/hardware.toml
docs/ops/maths.toml
docs/whats_new.md

Adds documentation for 2.2
Build the documentation and check for errors.  Worked okay for me but I couldn't generate the cheat sheet.
@unity2k steps up to the plate on this one.  Big thanks!

2.2 Documentation

---

CHANGELOG.md
docs/keys.md
docs/whats_new.md

Update docs for the fix for https://github.com/monome/teletype/issues/132
https://llllllll.co/t/teletype-in-cv-read-latency/10142
see the issue description

updated docs for IN latency fix

---

docs/ops/delay.toml
docs/ops/variables.toml
src/ops/delay.c

update docs for `DEL.X`, `DEL.R`, `J`, and `K`
additionally ran git-clang-format on `delay.c`
https://llllllll.co/t/teletype-3-feature-requests-and-discussion/16219/200?u=alphacactus
no code changes.  test if docs build.

update DEL.X, DEL.R, J, and K docs.  ran format on delay.c

---

CHANGELOG.md
src/ops/init.c

fixes issue #174 
https://llllllll.co/t/teletype-3-0/11232/391
see the issue

fix for issue #174

---

README.md

Update the link to the monome.org documentation in README.md.
https://llllllll.co/t/teletype-3-2-0-release/31530/4

update link to monome.org documentation

---

CHANGELOG.md
docs/whats_new.md

update changelog and what's new (which was also missing all 3.2 additions - is it actually used anywhere?)

update changelog and whats_new

---

simulator/Makefile
tests/Makefile

update test/sim makefiles

---

CHANGELOG.md
docs/ops/delay.toml
docs/whats_new.md
module/help_mode.c
src/match_token.rl
src/ops/delay.c
src/ops/delay.h
src/ops/op.c
src/ops/op_enum.h

Repeat of #210 but to `main` instead of `master`

Repeat #210 DEL.G

---

CHANGELOG.md
docs/whats_new.md
src/ops/patterns.c

fixes bug #268 
https://llllllll.co/t/teletype-4-0-0-pre-release-beta-ready-for-testing/45871/53
see #268

fix for #268

---

CHANGELOG.md
docs/whats_new.md

I missed that v4.0.0 was completed. This moves the updates into a new section

Separate post v4.0.0 changes

---

CHANGELOG.md
docs/whats_new.md
module/main.c

fixes issue #291 
n/a
see #291

reset M timer when changing metro rate

---

.github/workflows/test.yml

Builds the documentation PDF as part of the PR checks
Look at the artifacts for the Action on this PR
* (n/a) updated `CHANGELOG.md` and `whats_new.md`
* (n/a) updated the documentation
* (n/a) updated `help_mode.c` (if applicable)
* (n/a) run `make format` on each commit
* (n/a) run tests

Build documentation PDF in Actions workflow

---

.github/workflows/test.yml

Add cheat sheets to Actions artifacts
